### ISSUE TITLE
Why there is no normalization?

### ISSUE THREAD

**Issue by Godzilla0517** [VectorDB-NTU/Extended-RaBitQ#1]
Thanks for your work! I am interested in your proposed RaBitQ and Extended RaBitQ. But I have a question that I didn't find the normalization operation in your code，both RaBitQ and Extended RaBitQ. And in this repo,  I have seen `python/utils/preprocess.py` which is consist of normalization. But I don't see code using this function in the follow-up process. I'm too confused about this. Thank you!

$$
o:=\frac{o_{r}-c}{||o_{r}-c||}, q:=\frac{q_{r}-c}{||q_{r}-c||}
$$

**Comment by gaoj0017** [comment]
The normalization step is not explicitly reflected in the index phase. 

Let us assume that we are computing the quantization code for a vector. 

- In RaBitQ, the code is computed by checking the signs of each dimension. Clearly, the result is unchanged whether or not we normalize the vector. Thus, we don't need to physically normalize it in the index phase.
- In extended RaBitQ, the code is computed by a more complicated algorithm. In the code, we assure that the algorithm still produces correct quantization codes whether or not we normalize the vector physically. 

It is worth highlighting that when estimating distances based on the quantization codes, we still explicitly use the formula derived from normalization.

Please let me know if you have any further questions.

**Comment by Godzilla0517** [comment]
> The normalization step is not explicitly reflected in the index phase.
> 
> Let us assume that we are computing the quantization code for a vector.
> 
> * In RaBitQ, the code is computed by checking the signs of each dimension. Clearly, the result is unchanged whether or not we normalize the vector. Thus, we don't need to physically normalize it in the index phase.
> * In extended RaBitQ, the code is computed by a more complicated algorithm. In the code, we assure that the algorithm still produces correct quantization codes whether or not we normalize the vector physically.
> 
> It is worth highlighting that when estimating distances based on the quantization codes, we still explicitly use the formula derived from normalization.
> 
> Please let me know if you have any further questions.

Thank you for your reply! I always wondered if there was a step missing in the code. Clearly I'm stupid! And I also want to know are there future python extensions for RaBitQ or Extended RaBitQ? Thank you very much!

**Comment by gaoj0017** [comment]
Don't worry. In the newest project (https://github.com/gouyt13/SymphonyQG), we provided some interfaces in Python. We planned to release a Python interface for the very basic version of RaBitQ, but the project later becomes larger (Now we have several projects related to RaBitQ.). We are thinking how they can be integrated and organized in one library.

**Comment by Godzilla0517** [comment]
> Don't worry. In the newest project (https://github.com/gouyt13/SymphonyQG), we provided some interfaces in Python. We planned to release a Python interface for the very basic version of RaBitQ, but the project later becomes larger (Now we have several projects related to RaBitQ.). We are thinking how they can be integrated and organized in one library.

Thank you very much！
